### PR TITLE
Implement PriceByGroup

### PR DESCRIPTION
**Pull request by Importantus**

### CODE REVIEW

**Comment by hoppjan** [comment]
Pretty sure this fails at runtime. Have you tested it on your device?

**Comment by Importantus** [comment]
I'm not sure. When I run it, there is an error in android studio "unable to determine activity name". Don't know what it means, but the widget works.

**Comment by hoppjan** [comment]
Also: Not quite sure the prices should be `Float`.
We get them as `String`, are there good reasons to change that? 
Currency conversion will never come, since it does not make sense in this use case.
Wouldn't we be parsing the String to Floats just to reformat them afterwards for a text field?

**Comment by Importantus** [comment]
I think it's better to have the raw data in the right format, because that's what is expectable. If you get the prices as float, you are also completely free to choose how you want to display them (point instead of comma, with or without € etc).

**Comment by Importantus** [comment]
I have this feeling that now you just wanted to prove something 🤨😂 My floats would have worked much better there, but well, it'll do. xD

**Comment by hoppjan** [comment]
I misunderstood the whole thing! Missed the attached issue 🤦

**Comment by hoppjan** [comment]
We could remove the price from Meal class now ^^

**Review by hoppjan — APPROVED** [review]
I mostly reverted my stupid stuff from yesterday, and made a few small improvements

**Pull request merged**
