### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Importantus**
I added some more descriptions and installation instructions (which I totally wrote all by myself) and shamelessly placed links to @lomenzel 's and my own mensa projects.

### CODE REVIEW

**Comment by Importantus** [comment]
I'm not sure about the first step under "Release": Update the version in app/build.gradle.kts (e.g. 1.2.3) 🤷‍♂️

**Review by hoppjan — COMMENTED** [review]
It seems updating the `versionCode` is not present in the release section, but it is necessary for updates to work properly.
Android only compares the `versionCode` on update, and the update will only succeed with a bigger number than currently installed.

**Comment by Importantus** [comment]
I have edited the first step. I hope it is correct now and that `app/build.gradle.kts` is the right file. ^^

**Review by hoppjan — APPROVED** [review]
Looks fine

**Pull request merged**
