### PR TITLE
Change emojis to better reflect vegan vs vegetarian vs meat meal options

### LINKED ISSUE #22: Modify emojis
As a user, I would like to see at a glance whether a dish is vegan, vegetarian or with meat. For this, the emojis used so far should be modified so that meat dishes get a meat emoji and vegetarian dishes get an egg emoji.

### PR DESCRIPTION
**Pull request by Draculente**
Closes #22

### CODE REVIEW

**Comment by Importantus** [comment]
Noooo, I wanted to do that! 😢

**Review by hoppjan — CHANGES_REQUESTED** [review]
I asked some people how they feel about 🥚, but 🥦 is liked better than 🥚.
🥚 suggests egg-products, which is not necessarily the case.
The 🥩 I do like very much, though!

**Comment by Importantus** [comment]
Maybe we could follow the code used by the Studentenwerk which is 🌻 for vegan and 🌽 for vegetarian. I mean, it's also not intuitive and I have no idea why it's a 🌽 but at least it wouldn't be a new code?

**Review by hoppjan — COMMENTED** [review]
How is that?

**Review by hoppjan — APPROVED** [review]
I like it that way 🌻 🌽 🥩

**Review by Importantus — APPROVED** [review]
🌻

**Pull request merged**
